spring:
  profiles:
    active:
      - dev
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.artembogomolova.demo.webapp.dao.util.SQLLiteDialect
  datasource:
    driver-class-name: org.sqlite.JDBC
    continue-on-error: false
  liquibase:
    change-log: classpath*:db/changelog/db.changelog-master.yml
server:
  port: 8080
  compression:
    enabled: true
  ssl:
    enabled: true
    client-auth: none
    enabled-protocols:
      - TLSv1.2
      - TLSv1.3