name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-check-coverage:
    continue-on-error: false
    timeout-minutes: 6
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: fetch sources
        uses: actions/checkout@v2
      - name: build test certificates
        run: |
          chmod +x ./certificate/cert-build.sh &&./certificate/cert-build.sh
      - name: Build with Maven in docker
        run: |
          mvn -B package verify --file pom.xml \
          -Psonar-check,code-coverage-integration-test,code-coverage-test,code-quality \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.organization=${{ github.repository_owner }} \
          -Dsonar.host.url=https://sonarcloud.io
          mkdir coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: demo-spring-simple-webapp-with-tls
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.gz
          verbose: true
          file: ./target/site/jacoco/jacoco.xml
