name: Build and publish to registry
on:
  create:
    tag: [ v* ]

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  REGISTRY_URL: ghcr.io
jobs:
  realease-image-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: build test certificates
        run: |
          chmod +x ./certificate/cert-build.sh &&./certificate/cert-build.sh
      - name: build app
        run: chmod +x ./gradlew&& ./gradlew clean assemble
      - name: Build image
        run: |
          docker build . --file Dockerfile -t $IMAGE_NAME
      - name: login to registry
        run: |
          # Step 1: Authenticate
          echo "${{ secrets.CR_PAT }}" | docker login $REGISTRY_URL -u bogomolov-a-a --password-stdin
      - name: push image to GitHub Docker Registry
        run: |
          LIBRARY_IMAGE_ID=${{ github.repository_owner }}/$IMAGE_NAME/$IMAGE_NAME;
          IMAGE_ID=$REGISTRY_URL/$LIBRARY_IMAGE_ID
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          # Step 2: Tag
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          # Step 3: Publish
          docker push $IMAGE_ID:$VERSION
      - name: logout from registry
        run: |
          docker logout $REGISTRY_URL