name: Build and publish to registry
on:
  create:
    tag: [ v* ]

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
jobs:
  realease-image-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build test certificates
        run: |
          chmod +x ./certificate/cert-build.sh &&./certificate/cert-build.sh
      - name: build app
        run: mvn -B package verify --file pom.xml
      - name: Build image
        run: |
          docker build . --file Dockerfile -t $IMAGE_NAME

      - name: Log into GitHub Container Registry
        run:

      - name: Push image to GitHub Container Registry
        env:
          REGISTRY_URL: docker.pkg.github.com
        run: |

          LIBRARY_IMAGE_ID=${{ github.repository_owner }}/$IMAGE_NAME/$IMAGE_NAME;
          IMAGE_ID=$REGISTRY_URL/$LIBRARY_IMAGE_ID

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          # Step 1: Authenticate
          $ echo "${{ secrets.CR_PAT }}" | docker login $REGISTRY_URL -u bogomolov-a-a --password-stdin
          # Step 2: Tag
          $ docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          # Step 3: Publish
          $ docker push $IMAGE_ID:$VERSION