name: issue from sonar
on:
  schedule:
    - cron: "*/2 * * * *"
jobs:
  get-issue-from-sonar:
    continue-on-error: false
    runs-on: ubuntu-latest

    steps:
      - name: fetch sources
        uses: actions/checkout@v2
      - name: create github issues from sonar issues.
        env:
          GITHUB_REPO_ISSUE_URL: ${{ github.api_url }}/repos/${{ github.repository }}/issues
          SONAR_QUBE_PROJECT_ISSUE_URL: https://sonarcloud.io/api/issues/search?projectKeys=bogomolov-a-a_demo-spring-simple-webapp-with-tls
        run: chmod +x ./CI/issue-management.sh&&./CI/issue-management.sh
